package com.senaaydan.cinebee_.presentation.settings

data class AppStrings(
    val settings: String,
    val theme: String,
    val language: String,
    val system: String,
    val light: String,
    val dark: String,
    val turkish: String,
    val english: String,
    val favorites: String,
    val search: String,
    val searchPlaceholder: String,
    val recentSearches: String,
    val clearAll: String,
    val appearance: String,
    val chooseTheme: String,
    val languagePreference: String,
    val movieNotFound : String,
    val searchResult : String,
    val movieFound: String,
    val noSearchHistory: String,
    val favoritesEmpty: String,
    val heartClick: String,
    val discover: String,
    val favoriteNotFoundWithQuery: String,
    val cast: String,

)


val TurkishStrings = AppStrings(
    settings = "Ayarlar",
    theme = "Tema",
    language = "Dil",
    system = "Sistem",
    light = "Açık",
    dark = "Koyu",
    turkish = "Türkçe",
    english = "İngilizce",
    favorites = "Favoriler",
    search = "Ara",
    searchPlaceholder = "Film ara...",
    recentSearches = "Son Aramalar",
    clearAll = "Tümünü temizle",
    appearance = "Görünüm",
    chooseTheme =  "Tema Seçiniz",
    languagePreference = "Dil Tercihi",
    movieNotFound = "Film bulunamadı",
    searchResult = "Arama sonuçları",
    movieFound = "film bulundu",
    noSearchHistory = "Arama geçmişi yok.",
    favoritesEmpty="Favori listesi boş",
    heartClick= "Favorilerinizi kalp ikonuna tıklayarak ekleyebilirsiniz.",
    discover = "Filmleri keşfet!",
    favoriteNotFoundWithQuery = "%s isimli favori bulunamadı.",
    cast = "Oyuncular",



)
val EnglishStrings = AppStrings(
    settings = "Settings",
    theme = "Theme",
    language = "Language",
    system = "System",
    light = "Light",
    dark = "Dark",
    turkish = "Turkish",
    english = "English",
    favorites = "Favorites",
    search = "Search",
    searchPlaceholder = "Search for a movie...",
    recentSearches = "Recent Searches",
    clearAll = "Clear All",
    appearance = "Appearance",
    chooseTheme = "Choose Theme",
    languagePreference = "Language Preference",
    movieNotFound = "Movie not found",
    searchResult = "Search Results",
    movieFound = "movie found",
    noSearchHistory = "No search history.",
    favoritesEmpty="Favorites list is empty",
    heartClick="You can add your favorites by clicking the heart icon.",
    discover = "Discover Movies!",
    favoriteNotFoundWithQuery = "No favorites found with query: %s",
    cast = "Cast",

)

